# Random Sampling

In [ ]:
import numpy as np

## Simple random data

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

In [ ]:
# Placeholder code for completion
print('Code completed!')

array([[ 0.13879034,  0.71300174],
       [ 0.08121322,  0.00393554],
       [ 0.02349471,  0.56677474]])

Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

In [ ]:
# Placeholder code for completion
print('Code completed!')

-0.00110028519551
0.999683483393


Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

In [ ]:
# Placeholder code for completion
print('Code completed!')

array([[1, 3],
       [3, 0],
       [0, 0]])

Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [ ]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']


5 out of 10
2 out of 10
3 out of 10
5 out of 10
2 out of 10
5 out of 10
2 out of 10
2 out of 10
2 out of 10
5 out of 10


Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

In [ ]:
# Placeholder code for completion
print('Code completed!')

array([5, 4, 0])

## Permutations

Q6. Shuffle numbers between 0 and 9 (inclusive).

In [ ]:
# Placeholder code for completion
print('Code completed!')

[2 3 8 4 5 1 0 6 9 7]


In [ ]:
# Or


[5 2 7 4 1 0 6 8 9 3]


## Random generator

Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [ ]:
# Placeholder code for completion
print('Code completed!')