# Array creation routines

## Ones and zeros

In [2]:
import numpy as np

Create a new array of 2*2 integers, without initializing entries.



In [6]:
x = np.zeros([2,2], int)
x

array([[0, 0],
       [0, 0]])

Let X = np.array([1,2,3], [4,5,6], np.int32).
Create a new array with the same shape and type as X.

In [7]:
X = np.array([[1,2,3], [4,5,6]], np.int32)


Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [8]:
y = np.eye(3)
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a new array of 3*2 float numbers, filled with ones.

In [10]:
z = np.ones([3,2], float)
z

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [12]:
x = np.arange(4, dtype=np.int64)
x

array([0, 1, 2, 3])

Create a new array of 3*2 float numbers, filled with zeros.

In [14]:
z = np.zeros([3,2], float)
z

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [15]:
x = np.arange(4, dtype=np.int64)
x

array([0, 1, 2, 3])

Create a new array of 2*5 uints, filled with 6.

In [16]:
x = np.full((2, 5), 6, dtype=np.uint32)
x

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [19]:
x = np.arange(4, dtype=np.int64)
np.full_like(x, 6)

array([6, 6, 6, 6])

## From existing data

Create an array of [1, 2, 3].

In [20]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

Let x = [1, 2]. Convert it into an array.

In [21]:
x = [1,2]
np.array(x)

array([1, 2])

Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [22]:
X = np.array([[1, 2], [3, 4]])
matrix_X = np.matrix(X)
matrix_X

matrix([[1, 2],
        [3, 4]])

Let x = [1, 2]. Conver it into an array of `float`.

In [23]:
x = [1, 2]
np.array(x, float)

array([1., 2.])

Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [24]:
x = np.array([30])
x = x[0]
x


30

Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [25]:
x = np.array([1, 2, 3])
y = np.copy(x)
print(id(x), x)
print(id(y), y)

133128446065712 [1 2 3]
133128162503888 [1 2 3]


## Numerical ranges

Create an array of 2, 4, 6, 8, ..., 100.

In [27]:
np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [28]:
import numpy as np
np.linspace(3., 10., 50)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

In [29]:
np.logspace(np.log10(3), np.log10(10), 50, endpoint=False)

array([3.        , 3.07311512, 3.14801218, 3.22473461, 3.3033269 ,
       3.38383462, 3.46630445, 3.5507842 , 3.63732288, 3.72597064,
       3.81677891, 3.90980033, 4.00508884, 4.10269969, 4.20268948,
       4.3051162 , 4.41003923, 4.51751942, 4.62761908, 4.74040206,
       4.85593375, 4.97428114, 5.09551287, 5.21969922, 5.3469122 ,
       5.47722558, 5.61071491, 5.74745761, 5.88753297, 6.0310222 ,
       6.17800851, 6.32857712, 6.48281535, 6.64081263, 6.80266057,
       6.96845302, 7.13828612, 7.31225834, 7.49047055, 7.67302611,
       7.86003086, 8.05159323, 8.2478243 , 8.44883786, 8.65475046,
       8.86568151, 9.0817533 , 9.30309113, 9.52982335, 9.76208141])

## Building matrices

Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].

In [31]:
X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]])
X.diagonal()

array([ 0,  5, 10])

Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

In [32]:
# Create a 4x4 array filled with zeros
diagonal_array = np.zeros((4, 4), dtype=int)

# Set the diagonal elements to the desired values
np.fill_diagonal(diagonal_array, [1, 2, 3, 4])

diagonal_array

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Create an array which looks like below.
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

In [33]:
# Create a 3x5 array filled with zeros
arr = np.zeros((3, 5))

# Set the elements below the main diagonal to 1
for i in range(1, 3):
  for j in range(i):
    arr[i,j] = 1

arr

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

Create an array which looks like below.
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [34]:
# Create a 4x3 array filled with zeros
arr = np.zeros((4, 3), dtype=int)

# Fill the array with the desired values
values = [0, 4, 7, 10]
for i in range(4):
  for j in range(min(i + 1,3)):
    arr[i,j] = values[i] + j

arr

array([[ 0,  0,  0],
       [ 4,  5,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

Create an array which looks like below. array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6], [0, 8, 9], [0, 0, 12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])