# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
import torch


# Create random tensor
tensor_a = torch.rand(7, 7)
print(tensor_a, tensor_a.shape)

tensor([[0.6668, 0.5331, 0.6632, 0.9383, 0.1836, 0.7271, 0.6207],
        [0.6608, 0.6234, 0.2553, 0.8336, 0.8155, 0.5096, 0.6405],
        [0.7567, 0.8481, 0.6778, 0.3699, 0.6028, 0.2142, 0.7729],
        [0.2305, 0.6503, 0.1267, 0.3378, 0.0938, 0.3674, 0.6452],
        [0.6003, 0.5519, 0.8461, 0.8340, 0.1548, 0.8551, 0.0935],
        [0.7850, 0.8171, 0.8204, 0.9546, 0.4781, 0.9181, 0.6168],
        [0.7862, 0.7931, 0.3514, 0.3586, 0.9284, 0.4430, 0.3583]]) torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
tensor_b = torch.rand(1, 7)

# Perform matrix multiplication
tensor_c = torch.matmul(tensor_a, tensor_b.T)  # Transpose tensor_b
print(tensor_c, tensor_c.shape)

tensor([[1.9004],
        [2.1310],
        [2.2100],
        [1.0233],
        [1.7211],
        [2.4801],
        [2.1989]]) torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_a = torch.rand(7, 7)
tensor_b = torch.rand(1, 7)

# Matrix multiply tensors
tensor_c = torch.matmul(tensor_a, tensor_b.T)

print(tensor_c, tensor_c.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("Device:", device)
else:
    device = torch.device('cpu')
    print("GPU not available, using CPU instead.")

# Create two random tensors on GPU
tensor_a = torch.rand(2, 3).to(device)
tensor_b = torch.rand(2, 3).to(device)

print(tensor_a, tensor_b)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [6]:
# Perform matmul on tensor_A and tensor_B
tensor_c = torch.matmul(tensor_a, tensor_b.T)
print(tensor_c, tensor_c.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [7]:
# Find max
max_value = tensor_c.max()

# Find min
min_value = tensor_c.min()

print("Maximum value:", max_value)
print("Minimum value:", min_value)

Maximum value: tensor(0.5617, device='cuda:0')
Minimum value: tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [8]:
# Find arg max
max_index = tensor_c.argmax()

# Find arg min
min_index = tensor_c.argmin()

print("Maximum index:", max_index)
print("Minimum index:", min_index)

Maximum index: tensor(3, device='cuda:0')
Minimum index: tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [9]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_a = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_b = tensor_a.squeeze()

# Print out tensors and their shapes
print(tensor_a, tensor_a.shape)
print(tensor_b, tensor_b.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
